source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'BLE_Example' do
  pod 'BLE', :path => '../'
  pod 'SnapKit'
end

target 'BLE_Tests' do
  pod 'BLE', :path => '../'
end
